[service]
# root directory of the project
root = "."
start = "bash -c 'cd web && npx next start --hostname 0.0.0.0 --port 3000 & cd ../src && /opt/venv/bin/python agent.py start'"
build = """
# Docker build is automatic
"""
# Remove any Healthcheck Path to disable it completely
healthcheck = ""
restart_policy = "on-failure"
max_restart_retries = 10
